### ISSUE TITLE
How do you get this installed locally?

### ISSUE THREAD

**Issue by VinceG** [adambullmer/vue-cli-plugin-browser-extension#1]

**Comment by adambullmer** [comment]
I'll update the README, but you can add this:
- through the `vue ui` searching for `browser-extension`
- with `vue add browser-extension`
- with yarn/npm `yarn add vue-cli-plugin-browser-extension`, though you will miss out on generators/scaffolding when adding a plugin in this manner, so this is the least recommended way

**Comment by VinceG** [comment]
@adambullmer Thank You.
