### ISSUE TITLE
High vulnerability in dependencies -> copy webpack plugin -> serialize js

### ISSUE THREAD

**Issue by juannn91** [adambullmer/vue-cli-plugin-browser-extension#103]
**Describe the bug**

**To Reproduce**
run 'npm audit' after install of latest version

**Expected behavior**
0 vulnerabilities

**Screenshots**
![image](https://user-images.githubusercontent.com/2078073/97769962-1d90a980-1afd-11eb-9e05-777ada46f354.png)

**Reproducible Example**
|Name|Version|
|-------|--------|
| vue-cli-plugin-browser-extension| 0.25.0 |
| Operating System | MacOS Catalina v10.15.7  |
| Node | v12.18.3 |
| NPM/Yarn |6.14.8 |
| vue-cli | @vue/cli 4.5.8 |

**Additional context**

The same issue [here](https://github.com/vuejs/vue-cli/issues/5782) in **vue-cli** and they solve it by updating the **copy-webpack-plugin** the fix of this package issue is on the [copy-webpack-plugin@v5.1.2](https://github.com/webpack-contrib/copy-webpack-plugin/releases/tag/v5.1.2) I think this can be fixed by updating that copy-webpack-plugin package to a version >= 5.1.2

**Comment by adambullmer** [comment]
Released in v0.25.1
