### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by shash7** [adambullmer/vue-cli-plugin-browser-extension#137]
Seems like there are heaps of bugs regarding v3 manifest(mainly csp and background service workers) which haven't been resolved and no major updates have been made in this area.

So is this project dead? And if yes, what are the alternatives?

**Comment by ChxGuillaume** [comment]
Likely dead cause of the Manifest V3

I would love to find a good alternative :/

**Comment by jculverwell** [comment]
Maybe this https://github.com/sanyu1225/vue-cli-plugin-chrome-extension-cli .  Would love to hear what other people are using.

**Comment by Myzel394** [comment]
@jculverwell Is there also a Firefox version available?

**Comment by sherifmayika** [comment]
Finally I got Manifest 3 working in this after 10 days of research

**Comment by Myzel394** [comment]
@sherifmayika how?

**Comment by sherifmayika** [comment]
> @sherifmayika how?

https://github.com/adambullmer/vue-cli-plugin-browser-extension/issues/107 
followed this 
then dis some reaserch
where are you stuck at?

**Comment by sherifmayika** [comment]
> @jculverwell Is there also a Firefox version available?

with little tweak you can turn your product suitable for firefox

**Comment by JohnM-729** [comment]
@sherifmayika 

> disabled hot reload

Thanks for the link, it was very helpful!

What did you do to disable hot reloading besides pulling out the webpack-extension-reloader library, and nuking the references to the reloader in index.js? Anything else?

**Comment by adambullmer** [comment]
yes, I would mostly consider this a dead project. the vue community has dramatically changed the tooling ecosystem since this started (i.e. vite), manifest v3 has added some complexities to local development, and some of the existing livereload solutions never worked that well to name a few of the challenges in maintenance for this project. Some updates have been made to help existing projects limp along

**Comment by shash7** [comment]
Appreciate the closure @adambullmer 
Build my first product(Snapfont) on this years ago.
