### ISSUE TITLE
Add Installing Vue-Router and Vuex Options In Prompts

### ISSUE THREAD

**Issue by seanwu1105** [adambullmer/vue-cli-plugin-browser-extension#23]
I believe some relatively small-scale projects would not require Vue-Router or Vuex for popup and options pages. It could be great to add some options, which ask users whether to install Vue-Router or Vuex for popup or options (or both) pages, in installing prompts. This could help developers to decrease the total size of extension if the project does not need those unnecessary plugins.

**Comment by adambullmer** [comment]
I've been thinking about this one a bit. The inclusion of vue-router and vuex were largely a convenience, and not at all intended to bloat applications that do not need them. App scaffolding is for helping people get up and running quickly, over creating the most optimized app out of the box. It also tries to balance configuration with complexity, So while on the one hand, I would love to make another couple of scaffolding options, I don't want to inflate the complexity of the source code in this plugin with some options that aren't absolutely necessary to new projects getting started. Scaffolding also generally introduces some throw away boilerplate, so guess I didn't think twice about including these fairly common dependencies.

I would like to solve for the needs of the community and not just my own idea of what a baseline app should or should not look like. I'm open to the discussion of what features to make standard, and what to maybe include guidelines or recipes. A great opportunity is #24 requesting locales support that doesn't necessarily need scaffolding to get a project up and running.
