### ISSUE TITLE
Locales support

### ISSUE THREAD

**Issue by matrunchyk** [adambullmer/vue-cli-plugin-browser-extension#24]
Is it possible to have [locales](https://developer.chrome.com/extensions/manifest/default_locale) support?

I think it needs to add an extra `CopyWebpackPlugin` usage for `_locales` folder and maybe an extra check for `pluginOptions.manifestSync.includes('default_locale')`.

Awesome plugin, thank you!

**Comment by adambullmer** [comment]
Made a pull request enabling some basic support for locales. It handles some of the scaffolding, but Vue's default behavior of copying anything in the `public` directory into the root of the `dist` directory is really the only feature needed to enable internationalization. If you could make sure this behaves like you expect, I can get this merged and released.

Thank you for the suggestion!

**Comment by matrunchyk** [comment]
Thank you, the PR looks great to me! 😀
