### ISSUE TITLE
Uncaught (in promise) in popup

### ISSUE THREAD

**Issue by k1nghat** [adambullmer/vue-cli-plugin-browser-extension#33]
Uncaught (in promise) Objectmessage: "Could not establish connection. Receiving end does not exist."get message: ƒ ()arguments: (...)caller: (...)length: 0name: ""__proto__: ƒ ()[[Scopes]]: Scopes[0]__proto__: Object

i have a fresh vue cli install plus a fresh vue-cli-plugin-browser-extension install and get this error on serve.

**Comment by k1nghat** [comment]
not related but i didnt want to start a new issue for these, but why is there an index.js and routes.js instead of a single router.js?

should the top level `components` dir be used for everything or should there be a `components` dir inside of `options` and `popup`?

also, should the plugin follow the naming conventions of the vue cli? like `views` instead of `pages`?

**Comment by doutatsu** [comment]
@kinghat Have you gotten this to work? I am getting this error when trying to communicate from background to popup

**Comment by kinghat** [comment]
> @kinghat Have you gotten this to work? I am getting this error when trying to communicate from background to popup

honestly i dont remember this but if i closed it i dont think its an issue for me any longer :man_shrugging:
