### ISSUE TITLE
Content script entry missing from manifest.js

### ISSUE THREAD

**Issue by franciscolourenco** [adambullmer/vue-cli-plugin-browser-extension#41]
On a new project, selecting the content script option during generation, the content-script option is missing from manifest.json.

https://github.com/reproducing/vue-cli-plugin-browser-extension-manifest-content-script/blob/master/src/manifest.json

---- 

EDIT: there is also some indentation issue in [this line](https://github.com/reproducing/vue-cli-plugin-browser-extension-manifest-content-script/blob/5cce6180fbcb10bb25be0180f474b75f33fd4cb9/src/manifest.json#L30
)

**Comment by adambullmer** [comment]
When the manifest is scaffolded with a content script, the [activeTab](https://developer.chrome.com/extensions/activeTab) This is added by default based on google's docs on how to use [content scripts](https://developer.chrome.com/extensions/content_scripts#programmatic). As it stands right now, there isn't really a one size fits all scaffold, and this was the lest opinionated option to add to your manifest out of the box.

**Comment by franciscolourenco** [comment]
I was expecting the `content_scripts` option. As you said they both options are ways of executing content scripts. 

```json
  "content_scripts": [
    {
      "matches": ["*://*/*"],
      "js": ["content_scripts/content.js"]
    }
  ],
```


This would be quite permissive, but at the same time the scaffold already includes
```json
  "permissions": [ 
    "<all_urls>",
    "*://*/*"
  ]
```

If you keep it like it is, it would already be useful adding your explanation to the readme.

**Comment by franciscolourenco** [comment]
Closing this
