### ISSUE TITLE
Live reload clarification

### ISSUE THREAD

**Issue by franciscolourenco** [adambullmer/vue-cli-plugin-browser-extension#42]
Live reloading capabilities are mentioned a few times in the README, however this plugin does not support HMR.

It would be helpful if the distinction was made, and to know what live reload means exactly, in the context of the browser extension.

Thanks!

------------------

Related: 
- https://github.com/adambullmer/vue-cli-plugin-browser-extension/issues/36
- https://github.com/adambullmer/vue-cli-plugin-browser-extension/issues/40

**Comment by franciscolourenco** [comment]
Related: 
- https://github.com/adambullmer/vue-cli-plugin-browser-extension/issues/36
- https://github.com/adambullmer/vue-cli-plugin-browser-extension/issues/40

**Comment by adambullmer** [comment]
**Simple answer**: The webpack extensions used in this plugin claim livereload, but not Hot module reload. Nothing automatically refreshes your browser view for you when you make code changes.

**More complicated answer**: At present, nothing will reload the extension popup, options, or other pages. The webpack extension author does a good job explaining at a high level [what it does](https://github.com/rubenspgcavalcante/webpack-extension-reloader#what-it-does).

#### So, if it doesn't refresh the page for you, then what is it doing?
If you were to remove the `webpack-extention-reloader` plugin, here are the manual steps you would have to take every time you made a change to your code:

1. vue-cli/webpack already handle the rebuild of your application
1. go to the extensions page
1. locate your extension
1. click refresh (in chrome it is available at a top level as a circular arrow)
1. resume what you were doing, presumably in a separate tab

It doesn't seem like much, but by removing the need to constantly refresh the extension in the browser the development process is a little more streamlined, time will overall be saved, and it is easier for developers to develop browser extensions.

I do think you're right that the docs can be updated to clarify this better. Even though I wrote them, it took me a while to find the footnote about HMR not being supported. Some of my regular work is ramping down and I think I can dedicate some more time to maintenance here, as it looks like there are a few places for improvement, as well as much more community feedback than when I originally started.
