### ISSUE TITLE
Add support for devtools

### ISSUE THREAD

**Issue by Elazul** [adambullmer/vue-cli-plugin-browser-extension#44]
Hi!

Is there any plan for supporting https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Extending_the_developer_tools in the near future ?

Thanks for the good job !

**Comment by adambullmer** [comment]
That's always an option. It's been a while, but I think I was holding off to see if there was any interest, and to make sure that some of the bugs/snags were worked out before adding more facets to the app.

If you needed something in the short term, I believe you only need to:
- Add a new page to `vue.config.js` similar to how the others are added
- Clone another page into `/src/devtools/`
- Specify the devtools key into `manifest.json` using the output name from your page in `vue.config.js`

**Comment by Elazul** [comment]
Yes that's exactly what I did. I managed to merge devtools features with other stuff already generated by the plugin. Anyway it'd be great to keep improving the plugin with new APIs support.

Thanks!

**Comment by adambullmer** [comment]
Scaffolding has been added to `0.18.0`
