### ISSUE TITLE
killing the watch starts tossing connection errors in the background script

### ISSUE THREAD

**Issue by k1nghat** [adambullmer/vue-cli-plugin-browser-extension#47]
![image](https://user-images.githubusercontent.com/16073360/62159726-064e8500-b2d8-11e9-819e-f71e93ee820f.png)

is `ctrl+c` not the proper way to kill the process?
**edit**:
looks like its with `webpack-extension-reloader`: https://github.com/rubenspgcavalcante/webpack-extension-reloader/issues/30

**Comment by k1nghat** [comment]
https://github.com/rubenspgcavalcante/webpack-extension-reloader/issues/30

**Comment by adambullmer** [comment]
I think that's all to be expected if you kill the server that the front end expects to be running

**Comment by adambullmer** [comment]
Possibly on the webpack extension reloader side. I don't know their code well enough to make that claim for them. I think this is just one of those things that developers will have to deal with while we develop things.

Another workaround would be to run `yarn build` to generate a version of your code without the server.

**Comment by k1nghat** [comment]
> Another workaround would be to run `yarn build` to generate a version of your code without the server.

you mean to bypass running `webpack-extension-reloader` or to do it after you kill the process? because running it after you kill the process doesnt seem to help.

**Comment by adambullmer** [comment]
to bypass `webpack-extension-reloader` after you're done actively developing your extension. It's not great, but it at least removes the console errors

**Comment by adambullmer** [comment]
closing as there is nothing this package can do to resolve the issues. Errors lie with how every live reload server operates. The issues are more prominent because extensions can live on every page and continue to throw errors after dev builds have been killed
