### ISSUE TITLE
content_security_policy unsafe-eval

### ISSUE THREAD

**Issue by franciscolourenco** [adambullmer/vue-cli-plugin-browser-extension#54]
I'm trying to edit the `content_security_policy` but I see that this plugin is was setting its own, only during development, with `unsafe-eval`, I guess for the purposes of HMR or sourcemap eval?

Is is currently possible to set a custom `content_security_policy` in such a way that `unsafe-eval` is removed in production?

Thanks!

**Comment by adambullmer** [comment]
Yes, this can be done. Will probably take some time, but if you need it now, you can use the `manifestTransformer` option to provide a function to do it yourself.

**Comment by franciscolourenco** [comment]
Thanks for the tip!

**Comment by adambullmer** [comment]
Automatic removal of `'unsafe-eval'` in production builds should be available in `0.22.1`
