### ISSUE TITLE
Fresh install with vue cli 4 leads to several errors in chrome extension

### ISSUE THREAD

**Issue by tcamde** [adambullmer/vue-cli-plugin-browser-extension#66]
I just tried to setup a project with vue cli 4 and I got as far as generating the right output files with npm run serve and npm run build.

However the chrome extension logs several error messages:
![chromlogs](https://user-images.githubusercontent.com/26344624/68754336-c7cea300-0606-11ea-8f00-6ef7fa32b891.png)

1. found unexpected key 'browser_style'
`  "options_ui": {
    "page": "options.html",
    "browser_style": true
  },`

2. Uncaught SyntaxError: missing ) after argument list
`js/popup.js:1209 (anonymous function)`

3. Uncaught SyntaxError: missing ) after argument list
`js/background.js:1209 (anonymous function)`

4. Uncaught (in promise) [object Object]
`js/chunk-vendors.cb8df399.js:7 (anonymous function)`

The project is an empty setup with vue cli 4, including vuex and eslint.
In development mode the popup doesn't display anything, while the build files will display the helloworld component in the popup.

**Comment by adambullmer** [comment]
Looks like the base vue webpack config adds optimization flags into the development builds now.
