### ISSUE TITLE
Devtools failed to parse souce map on chromium based browser(vivaldi)

### ISSUE THREAD

**Issue by AmrBinBashir** [adambullmer/vue-cli-plugin-browser-extension#78]
**Describe the bug**
`Devtools failed to parse souce map` on chromium based browser(vivaldi) but kinda works fine in firefox. in firefox it some times gives this error `Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://054d9919-352c-450b-8d8b-46938d84cf48/js/background.js
Source Map URL: browser-polyfill.js.map`

**To Reproduce**
just use yarn build and load the extension into the browser and ctrl shift I and check console tab

**Reproducible Example**
https://github.com/AmrBinBashir/Kura

|Name|Version|
|-------|--------|
| vue-cli-plugin-browser-extension| Latest|
| Operating System |  Win10 1909 build 18363.657 |
| Node | 12.3.0| 
| NPM/Yarn | Yarn 1.22| 
| vue-cli | 4.2| 
| vue-cli-service | |
| browser | Vivaldi 2.11|

**Comment by robertdavid010** [comment]
Any information on why this was closed? I am having the same issue.
