### ISSUE TITLE
RFC: Should we pre-create an « icons » folder?

### ISSUE THREAD

**Issue by Kocal** [adambullmer/vue-cli-plugin-browser-extension#9]
I don't see it anymore in template, is there a reason for that?
Would not be a good move to pre-create an `icons` folder like it's done [here](https://github.com/Kocal/vue-web-extension/tree/master/template/src/icons) ?

I think it would be nice to pre-create it, because it will prevent some errors about not existing icon when loading extension into browser. :+1: 

Thanks for your time

**Comment by adambullmer** [comment]
Yup, there was totally supposed to be one. Had an issue with mac and case insensitive gitignores 😑. Great catch!
