### ISSUE TITLE
More permissive license

### ISSUE THREAD

**Issue by franciscolourenco** [adambullmer/vue-cli-plugin-browser-extension#91]
GPLv3 says that larger works, which include this package, need to make their source code available under the same license. This sounds quite a lot for a development package, which can prevent it from being used by many projects.

>"Permissions of this strong copyleft license are conditioned on making available complete source code of licensed works and modifications, **which include larger works using a licensed work**, under the same license. 

Would you consider switching to MIT license?

Cheers!

**Comment by adambullmer** [comment]
I think this falls under the exception of a well separated program as this is used for building and locally serving an app, but not at runtime. I'm by no means a law expert, its just how I've understood this clause to mean that application source wouldn't have to be published if this plugin were to be used as a part of the build routine. I think if necessary I could convert it to a LGPLv3 license specifying the use through the vue-cli plugin interface?

https://www.gnu.org/licenses/gpl-faq.html#GPLInProprietarySystem
> If the two programs remain well separated, like the compiler and the kernel, or like an editor and a shell, then you can treat them as two separate programs...

Is this currently a blocker you're facing, or just a general note about license permissiveness?

**Comment by franciscolourenco** [comment]
I agree that it falls into that exception, but I'm no lawyer and there is a risk for different interpretations. 
Out of 60 direct dependencies, this is the only GPL, with 55 being MIT, so I was wondering if there is a good reason for it.
It's not a blocker, just a concern. Thanks!

**Comment by franciscolourenco** [comment]
Any chance of a resolution on this? 
I've analyzed my `node_modules` dire and out of ~3000 packages this was the only GPL :/ 
Thanks!

**Comment by franciscolourenco** [comment]
LGPLv3 would work :)

**Comment by franciscolourenco** [comment]
Sorry to ping again but this has became a blocker. Thanks!

**Comment by adambullmer** [comment]
just published a release 0.25.0 that is not licensed under lgplv3.

**Comment by franciscolourenco** [comment]
Thanks!
